---
# stolen from: https://secure.n-able.com/webhelp/NC_7-2-0_Cust_en/Content/N-central/Services/Services_PrinterTonerLevel.html
sensor:
  - platform: snmp
    name: kyocera_total_pages
    host: kyocera
    baseoid: 1.3.6.1.2.1.43.10.2.1.4.1.1
    accept_errors: true
    unit_of_measurement: 'pages'
  - platform: snmp
    name: kyocera_black_capacity
    host: kyocera
    baseoid: 1.3.6.1.2.1.43.11.1.1.8.1.4
    accept_errors: true
    unit_of_measurement: 'pages'
  - platform: snmp
    name: kyocera_black_level
    host: kyocera
    baseoid: 1.3.6.1.2.1.43.11.1.1.9.1.4
    accept_errors: true
    unit_of_measurement: 'pages'
  - platform: snmp
    name: kyocera_yellow_capacity
    host: kyocera
    baseoid: 1.3.6.1.2.1.43.11.1.1.8.1.3
    accept_errors: true
    unit_of_measurement: 'pages'
  - platform: snmp
    name: kyocera_yellow_level
    host: kyocera
    baseoid: 1.3.6.1.2.1.43.11.1.1.9.1.3
    accept_errors: true
    unit_of_measurement: 'pages'
  - platform: snmp
    name: kyocera_magenta_capacity
    host: kyocera
    baseoid: 1.3.6.1.2.1.43.11.1.1.8.1.2
    accept_errors: true
    unit_of_measurement: 'pages'
  - platform: snmp
    name: kyocera_magenta_level
    host: kyocera
    baseoid: 1.3.6.1.2.1.43.11.1.1.9.1.2
    accept_errors: true
    unit_of_measurement: 'pages'
  - platform: snmp
    name: kyocera_cyan_capacity
    host: kyocera
    baseoid: 1.3.6.1.2.1.43.11.1.1.8.1.1
    accept_errors: true
    unit_of_measurement: 'pages'
  - platform: snmp
    name: kyocera_cyan_level
    host: kyocera
    baseoid: 1.3.6.1.2.1.43.11.1.1.9.1.1
    accept_errors: true
    unit_of_measurement: 'pages'
