---
image: docker:latest

stages:
  - preflight
  - homeassistant
  - esphome

# Generic preflight template
.preflight: &preflight
  stage: preflight
  tags:
    - shared

# Generic Home Assistant template
.ha: &ha
  stage: homeassistant
  variables:
    PYTHONPATH: "/usr/src/app:$PYTHONPATH"
  before_script:
    - cp -R .stubs/fake_hassio_secrets.yaml ./secrets.yaml
    - mkdir -p secrets/adb
    - cp .stubs/fake_adb_key secrets/adb/hassio
    - cp .stubs/fake_adb_key.pub secrets/adb/hassio.pub
    - cd bash_scripts
    - ./install.sh build
    - cd ..
    - python -m homeassistant --version
  script:
    - |
      python -m homeassistant \
        --config . \
        --script check_config \
        --info all
  tags:
    - shared

# Generic ESPHome template
.esphome: &esphome
  stage: esphome
  variables:
    PYTHONPATH: "/usr/src/app:$PYTHONPATH"
  script:
    - esphome dummy.yaml version
    - cp -R ./.stubs/fake_esphome_secrets.yaml ./esphome/secrets.yaml
    - cp -R .stubs/fake_hassio_secrets.yaml ./secrets.yaml
    - |
      for file in $(find \
        ./esphome \
        -type f \
        -name "*.yaml"\
        -not -name "secrets.yaml" \
        -not -name "template_*.yaml"
        ); do
        echo working on $file
        esphome $file config
        esphome $file compile
      done
  tags:
    - shared

# Preflight jobs
shellcheck:
  <<: *preflight
  image:
    name: koalaman/shellcheck-alpine:stable
    entrypoint: [""]
  before_script:
    - shellcheck --version
    - apk --no-cache add grep
    - |
      find . -type f -print0 | \
        xargs -0 sed -i 's:#!/usr/bin/with-contenv bash:#!/bin/bash:g'
  script:
    - |
      for file in $(grep -IRl "#\!\(/usr/bin/env \|/bin/\)" --exclude-dir ".git" "${ADDON_TARGET}"); do
        if ! shellcheck $file; then
          export FAILED=1
        else
          echo "$file OK"
        fi
      done
      if [ "${FAILED}" = "1" ]; then
        exit 1
      fi

yamllint:
  <<: *preflight
  image: sdesbure/yamllint
  before_script:
    - yamllint --version
  script:
    - yamllint .

jsonlint:
  <<: *preflight
  image: sahsu/docker-jsonlint
  before_script:
    - jsonlint --version || true
  script:
    - |
      for file in $(find . -type f -name "*.json"); do
        if ! jsonlint -q $file; then
          export FAILED=1
        else
          echo "$file OK"
        fi
      done
      if [ "${FAILED}" = "1" ]; then
        exit 1
      fi

markdownlint:
  <<: *preflight
  image:
    name: ruby:alpine
    entrypoint: [""]
  before_script:
    - gem install mdl
    - mdl --version
  script:
    - mdl --style all --warnings .

# Home Assistant test jobs
ha-latest:
  <<: *ha
  image:
    name: homeassistant/home-assistant:latest
    entrypoint: [""]

ha-rc:
  <<: *ha
  image:
    name: homeassistant/home-assistant:rc
    entrypoint: [""]
  allow_failure: true

ha-dev:
  <<: *ha
  image:
    name: homeassistant/home-assistant:dev
    entrypoint: [""]
  allow_failure: true

# ESPHome test jobs
esphome-latest:
  <<: *esphome
  image:
    name: esphome/esphome:latest
    entrypoint: [""]

esphome-beta:
  <<: *esphome
  image:
    name: esphome/esphome:beta
    entrypoint: [""]
  allow_failure: true

esphome-dev:
  <<: *esphome
  image:
    name: esphome/esphome:dev
    entrypoint: [""]
  before_script:
    - pip3 install https://github.com/esphome/esphome/archive/dev.zip
  allow_failure: true
