- id: '1555071586293'
  alias: Dishwasher finished (Alexa)
  trigger:
  - entity_id: binary_sensor.dishwasher
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      data:
        type: announce
      message: Spülmaschine ist fertig
    service: notify.alexa_media_echo_weiss_wohnzimmer
- id: '1555141985602'
  alias: Washing machine finished (Alexa)
  trigger:
  - entity_id: binary_sensor.washing_machine
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      data:
        type: announce
      message: Waschmaschine ist fertig
    service: notify.alexa_media_echo_weiss_wohnzimmer
- id: '1555142049412'
  alias: Dryer finished (Alexa)
  trigger:
  - entity_id: binary_sensor.dryer
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      data:
        type: announce
      message: Trockner ist ferting
    service: notify.alexa_media_echo_weiss_wohnzimmer
- id: '1555147661344'
  alias: Dishwasher finished (text based)
  trigger:
  - entity_id: binary_sensor.dishwasher
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Spülmaschine ist fertig! @insane
    service: notify.matrix_notify
- id: '1555147824684'
  alias: Dryer finished (text based)
  trigger:
  - entity_id: binary_sensor.dryer
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Trockner ist fertig! @insane
    service: notify.matrix_notify
- id: '1555147878801'
  alias: Washing machine finished (text based)
  trigger:
  - entity_id: binary_sensor.washing_machine
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Waschmaschine ist fertig! @insane
    service: notify.matrix_notify
- id: '1555148232966'
  alias: Matrix bot commands
  trigger:
  - event_data:
      command: my_command
    event_type: matrix_command
    platform: event
  condition: []
  action:
  - data:
      message: Hi
    service: notify.matrix_notify
- id: '1556031753506'
  alias: Bathroom cover down
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data:
      entity_id: cover.401401
      position: '45'
    service: cover.set_cover_position
- id: '1556032240161'
  alias: Bathroom cover up
  trigger:
  - event: sunrise
    platform: sun
  - at: 09:30:00
    platform: time
  condition:
  - after: sunrise
    condition: sun
  - after: 09:30:00
    condition: time
  action:
  - data:
      entity_id: cover.401401
    service: cover.open_cover
- id: '1576417848048'
  alias: Meteor on
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.jeq0463769_unused
    service: switch.turn_on
- id: '1576417905727'
  alias: Meteor off
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.jeq0463769_unused
    service: switch.turn_off
