- id: '1555071586293'
  alias: Dishwasher finished (Alexa)
  trigger:
  - entity_id: binary_sensor.dishwasher
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      data:
        type: announce
      message: Spülmaschine ist fertig
    service: notify.alexa_media_echo_weiss_wohnzimmer
- id: '1555141985602'
  alias: Washing machine finished (Alexa)
  trigger:
  - entity_id: binary_sensor.washing_machine
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      data:
        type: announce
      message: Waschmaschine ist fertig
    service: notify.alexa_media_echo_weiss_wohnzimmer
- id: '1555142049412'
  alias: Dryer finished (Alexa)
  trigger:
  - entity_id: binary_sensor.dryer
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      data:
        type: announce
      message: Trockner ist ferting
    service: notify.alexa_media_echo_weiss_wohnzimmer
- id: '1555147661344'
  alias: Dishwasher finished (text based)
  trigger:
  - entity_id: binary_sensor.dishwasher
    platform: state
    to: 'off'
  condition: []
  action:
  - service: notify.telgram_clay
    data:
      title: Spülmaschine fettig
      message: 'Hallo,

        ich bin deine Spülmaschine. Ich wäre jetzt fertig.


        LG

        Deine Spülmaschine

        '
  - service: notify.telgram_nancy
    data:
      title: Spülmaschine fettig
      message: 'Hallo,

        ich bin deine Spülmaschine. Ich wäre jetzt fertig.


        LG

        Deine Spülmaschine

        '
  mode: single
- id: '1555147824684'
  alias: Dryer finished (text based)
  trigger:
  - entity_id: binary_sensor.dryer
    platform: state
    to: 'off'
  condition: []
  action:
  - service: notify.telgram_clay
    data:
      title: Trockner ferting
      message: 'Hallo,

        ich bin dein Trockner. Ich wäre jetzt ferting.


        LG

        Dein Trockner

        '
  - service: notify.telgram_nancy
    data:
      title: Trockner ferting
      message: 'Hallo,

        ich bin dein Trockner. Ich wäre jetzt ferting.


        LG

        Dein Trockner

        '
  mode: single
- id: '1555147878801'
  alias: Washing machine finished (text based)
  trigger:
  - entity_id: binary_sensor.washing_machine
    platform: state
    to: 'off'
  condition: []
  action:
  - service: notify.telgram_clay
    data:
      title: Waschmaschine fertig
      message: 'Hallo,

        ich bin deine Waschmaschine. Ich wäre jetzt fertig.


        LG

        Deine Waschmaschine

        '
  - service: notify.telgram_nancy
    data:
      title: Waschmaschine fertig
      message: 'Hallo,

        ich bin deine Waschmaschine. Ich wäre jetzt fertig.


        LG

        Deine Waschmaschine

        '
  mode: single
- id: '1555148232966'
  alias: Matrix bot commands
  trigger:
  - event_data:
      command: my_command
    event_type: matrix_command
    platform: event
  condition: []
  action:
  - data:
      message: Hi
    service: notify.matrix_notify
- id: '1556031753506'
  alias: Bathroom cover down
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data:
      entity_id: cover.401401
      position: '45'
    service: cover.set_cover_position
- id: '1556032240161'
  alias: Bathroom cover up
  trigger:
  - event: sunrise
    platform: sun
  - at: 09:30:00
    platform: time
  condition:
  - after: sunrise
    condition: sun
  - after: 09:30:00
    condition: time
  action:
  - data:
      entity_id: cover.401401
    service: cover.open_cover
- id: '1607873437066'
  alias: Mara warning 1 (turn on light)
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 9d95a55f3c5311eb8cc08bd225275d27
    entity_id: binary_sensor.tradfri_motion_sensor_01
    domain: binary_sensor
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_pct: 80
      color_name: green
    entity_id: light.living_room_bulb01
  mode: single
- id: '1607873478722'
  alias: Mara warning 2 (turn off light)
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 9d95a55f3c5311eb8cc08bd225275d27
    entity_id: binary_sensor.tradfri_motion_sensor_01
    domain: binary_sensor
  condition: []
  action:
  - type: turn_off
    device_id: 778fa2f50ecc3b5c5814a04dded34f4b
    entity_id: light.living_room_bulb01
    domain: light
  mode: single
- id: '1607880929423'
  alias: Mara warning 3 (Alexa)
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 9d95a55f3c5311eb8cc08bd225275d27
    entity_id: binary_sensor.tradfri_motion_sensor_01
    domain: binary_sensor
  condition: []
  action:
  - service: notify.alexa_echo_weiss_wohnzimmer
    data:
      message: Es gibt interessante Bewegungen im ersten Stock
      data:
        type: announce
  mode: single
- id: '1616251001045'
  alias: Set warm_day_fixed
  description: ''
  trigger:
  - platform: time
    at: 05:30
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.warm_day_realtime
        state: 'off'
      sequence:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.warm_day_fixed
    default:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.warm_day_fixed
  mode: single
- id: '1637646141951'
  alias: Vorgarten aus bei Sonnenaufgang
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: +00:05:00
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.vorgarten_licht_1
  mode: single
