---
sensor:
  - platform: darksky
    api_key: !secret darksky_token
    forecast:
      - 0
    monitored_conditions:
      - summary
      - icon
      - temperature
      - precip_probability
      - precip_type
      - temperature_high
      - temperature_low
      - uv_index
    scan_interval:
      minutes: 5
