esphome:
  name: bad_hdmi_switch
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:
  hardware_uart: UART1
# Enable Home Assistant API
api:

web_server:
  port: 80

uart:
  baud_rate: 9600
  tx_pin: GPIO1
  rx_pin: GPIO3

text_sensor:
  - platform: homeassistant
    name: "HDMI Input Selection"
    entity_id: input_select.bedroom_hdmi_switch
    on_value:
      then:
        - if:
            condition:
              lambda: |-
                return x == "Fire TV";
            then:
              switch.turn_on: input1
        - if:
            condition:
              lambda: |-
                return x == "SteamLink";
            then:
              switch.turn_on: input2
        - if:
            condition:
              lambda: |-
                return x == "Satellite Receiver";
            then:
              switch.turn_on: input3
        - if:
            condition:
              lambda: |-
                return x == "Nintendo Switch";
            then:
              switch.turn_on: input4
        - if:
            condition:
              lambda: |-
                return x == "SNES";
            then:
              switch.turn_on: input5
switch:
  - platform: template
    name: "Bedroom HMDI switch power"
    turn_on_action:
      - switch.turn_on: poweron
    turn_off_action:
      - switch.turn_on: poweroff
    optimistic: true

  - platform: uart
    id: poweroff
    data: 'poweroffR'
  - platform: uart
    id: poweron
    data: 'poweronR'
  - platform: uart
    id: input1
    name: "Input 1"
    data: 'port0R'
  - platform: uart
    id: input2
    name: "Input 2"
    data: 'port1R'
  - platform: uart
    id: input3
    name: "Input 3"
    data: 'port2R'
  - platform: uart
    id: input4
    name: "Input 4"
    data: 'port3R'
  - platform: uart
    id: input5
    name: "Input 5"
    data: 'port4R'
