esphome:
  name: ble_sniffer
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

time:
  - platform: sntp
    on_time:
      - seconds: 0
        minutes: 37
        hours: 4
        then:
          - switch.toggle: restart_sw

web_server:

esp32_ble_tracker:

sensor:
  - platform: uptime
    name: "ble_sniffer Uptime Sensor"
  - platform: xiaomi_hhccjcy01
    mac_address: !secret xiaomi_miflora_device01
    temperature:
      name: "Strawberry Temperature"
    moisture:
      name: "Strawberry Moisture"
    illuminance:
      name: "Strawberry Illuminance"
    conductivity:
      name: "Strawberry Soil Conductivity"
    battery_level:
      name: "Strawberry Battery Level"

switch:
  - platform: restart
    id: restart_sw
    name: "ble_sniffer restart"
