esphome:
  name: display01
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:

spi:
  clk_pin: D1
  mosi_pin: D0

font:
  - file: "assets/fonts/Roboto-Medium.ttf"
    id: roboto_20
    size: 20
    glyphs: '!"%()+,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz*'

time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: homeassistant
    id: dishwasher
    entity_id: binary_sensor.dishwasher
  - platform: homeassistant
    id: washing_machine
    entity_id: binary_sensor.washing_machine
  - platform: homeassistant
    id: dryer
    entity_id: binary_sensor.dryer
  - platform: homeassistant
    id: door
    entity_id: binary_sensor.turkontakt_terasse_state

sensor:
    - platform: homeassistant
      id: outside_temp
      entity_id: sensor.aussensensor_temperature
    - platform: homeassistant
      id: living_room_temp
      entity_id: sensor.living_room_temp
    - platform: homeassistant
      id: diesel
      entity_id: sensor.avia_axpress_steinheim_diesel
    - platform: homeassistant
      id: benzin
      entity_id: sensor.avia_axpress_steinheim_e5
    - platform: dht
      pin: D6
      model: DHT22
      temperature:
        name: "Display temp"
        id: local_temp
        # filters:
        #   - calibrate_linear:
        #     - 26.9 -> 23.7
      humidity:
        name: "Display humidity"
        id: local_humidity
      #   filters:
      #     - calibrate_linear:
      #       - 28 -> 32
display:
  - platform: waveshare_epaper
    cs_pin: D2
    dc_pin: D3
    busy_pin: D5
    reset_pin: D4
    model: 4.20in
    lambda: |-
      it.strftime(0, 0, id(roboto_20), "%H:%M", id(homeassistant_time).now());
      it.strftime(0, 25, id(roboto_20), "%a, %d.%m", id(homeassistant_time).now());

      it.printf(0, 90, id(roboto_20), "states: WM: %d, T: %d, SM: %d, Tuer: %d",
              id(washing_machine).state, id(dishwasher).state, id(dryer).state, id(door).state );

      it.printf(0, 120, id(roboto_20), "Temps: WZ: %.1f, D: %.1f, L: %.1f",
              id(living_room_temp).state, id(outside_temp).state, id(local_temp).state );
      it.printf(0, 160, id(roboto_20), "Sprit: Benzin: %.3f, Diesel: %.3f",
                id(benzin).state, id(diesel).state );
    update_interval: 1min
