esphome:
  name: display01
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

status_led:
  pin: GPIO2

web_server:

# deep_sleep:
#   id: deep_sleep_1
#   run_duration: 10s
#   sleep_duration: 45s

spi:
   clk_pin: D2
   mosi_pin: D1

font:
  - file: "assets/fonts/Roboto-Medium.ttf"
    id: roboto_20
    size: 20
    glyphs: '!"%()+,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz*'
  - file: "assets/fonts/Roboto-Medium.ttf"
    id: roboto_26
    size: 26
    glyphs: '!"%()+,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz*'
  - file: "assets/fonts/Roboto-Medium.ttf"
    id: roboto_18
    size: 18
    glyphs: '!"%()+,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz*'

image:
  - file: "assets/mdi/pine-tree_24.png"
    id: pine_tree_24
  - file: "assets/mdi/sofa_24.png"
    id: sofa_24
  - file: "assets/mdi/wall_24.png"
    id: wall_24
  - file: "assets/mdi/temperature-celsius_36.png"
    id: temperature_36

time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: homeassistant
    id: dishwasher
    entity_id: binary_sensor.dishwasher
  - platform: homeassistant
    id: washing_machine
    entity_id: binary_sensor.washing_machine
  - platform: homeassistant
    id: dryer
    entity_id: binary_sensor.dryer
  - platform: homeassistant
    id: door
    entity_id: binary_sensor.turkontakt_terasse_state

sensor:
    - platform: homeassistant
      id: outside_temp
      entity_id: sensor.aussensensor_temperature
    - platform: homeassistant
      id: living_room_temp
      entity_id: sensor.living_room_temp
    - platform: homeassistant
      id: diesel
      entity_id: sensor.avia_axpress_steinheim_diesel
    - platform: homeassistant
      id: benzin
      entity_id: sensor.avia_axpress_steinheim_e5
    - platform: dht
      pin: D7
      model: DHT22
      temperature:
        name: "Display temp"
        id: local_temp
        # filters:
        #   - calibrate_linear:
        #     - 26.9 -> 23.7
      humidity:
        name: "Display humidity"
        id: local_humidity
      #   filters:
      #     - calibrate_linear:
      #       - 28 -> 32
display:
  - platform: waveshare_epaper
    cs_pin: D3
    dc_pin: D4
    busy_pin: D5
    reset_pin: D6
    model: 4.20in
    update_interval: 1min
    lambda: |-
      // printing time and date
      it.strftime(15, 5, id(roboto_26), "%H:%M", id(homeassistant_time).now());
      it.strftime(10, 35, id(roboto_18), "%a, %d.%m", id(homeassistant_time).now());
      // line after time
      it.line(0, 65, 399, 65);
      it.line(0, 66, 399, 66);

      // circles and symbols for the temperature
      // outside
      it.image(0, 70, id(temperature_36));

      it.image(58, 118, id(pine_tree_24));
      it.circle(70, 100, 30);
      it.circle(70, 100, 31);

      // living room
      it.image(138, 118, id(sofa_24));
      it.circle(150, 100, 30);
      it.circle(150, 100, 31);

      // local temperature
      it.image(218, 118, id(wall_24));
      it.circle(230, 100, 30);
      it.circle(230, 100, 31);

      // values for the temperature
      it.printf(45, 100 , id(roboto_26), "%.1f", id(outside_temp).state);
      it.printf(125, 100 , id(roboto_26), "%.1f", id(living_room_temp).state);
      it.printf(205, 100 , id(roboto_26), "%.1f", id(local_temp).state);

      // separator line
      it.line(0, 144, 399, 144);
      it.line(0, 145, 399, 145);

      // test values
      it.printf(0, 225, id(roboto_20), "states: WM: %d, T: %d, SM: %d, Tuer: %d",
              id(washing_machine).state, id(dishwasher).state, id(dryer).state, id(door).state );

      it.printf(0, 275, id(roboto_20), "Sprit: Benzin: %.3f, Diesel: %.3f",
                id(benzin).state, id(diesel).state );
