substitutions:
  plug_name: "livingroom_tv_power"
  # Higher value gives lower watt readout
  current_res: "0.00221"
  # Lower value gives lower voltage readout
  voltage_div: "955"
  connected_device_standby_threshold: "5.0"
  connected_device_off_delay: "0ms"

<<: !include template_stealth_power_monitor_gosund_sp1.yaml
