---
esphome:
  name: rfidtest
  platform: ESP32
  board: lolin_d32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:

spi:
  clk_pin: GPIO18
  miso_pin: GPIO19
  mosi_pin: GPIO23

pn532:
  cs_pin: GPIO22
  update_interval: 1s

binary_sensor:
  - platform: pn532
    uid: 04-26-8A-CA-DD-4C-80
    name: "Yoshi Amiibo"
    on_press:
      then:
        - switch.turn_on: led

switch:
  - platform: gpio
    name: "led"
    pin: GPIO05
    id: led
    inverted: true
    on_turn_on:
      - delay: 5000ms
      - switch.turn_off: led
