---
automation:
  - alias: "Kinderzimmer cover down"
    trigger:
      platform: sun
      event: sunset
      offset: '00:00:05'
    condition:
      condition: template
      value_template: "{{ state_attr('cover.4055f8', 'current_position') > 60 }}"
    action:
      data:
        entity_id: cover.4055f8
        position: '45'
      service: cover.set_cover_position
  - alias: "Kinderzimmer cover up (cold days)"
    trigger:
      - at: '09:30:00'
        platform: time
    condition:
      - condition: template
        value_template: "{{ states.sensor.dark_sky_daytime_high_temperature_0d.state | float < 22.0 }}"
    action:
      - data:
          entity_id: cover.4055f8
        service: cover.open_cover
  - alias: "Kinderzimmer cover up (warm days)"
    trigger:
      - at: '14:30:00'
        platform: time
    condition:
      condition: template
      value_template: "{{ states.sensor.dark_sky_daytime_high_temperature_0d.state | float >= 22.0 }}"
    action:
      data:
        entity_id: cover.4055f8
      service: cover.open_cover
